SELECT ANIMAL_ID, NAME, DATETIME
FROM ANIMAL_INS
ORDER by NAME DESC, DATETIME DESC

SELECT ANIMAL_ID, NAME
FROM ANIMAL_INS
WHERE INTAKE_CONDITION = "Sick"

SELECT NAME
FROM ANIMAL_INS
ORDER by DATETIME
LIMIT 1

SELECT count(DISTINCT NAME)
FROM ANIMAL_INS

SELECT count(*)
FROM ANIMAL_INS


SELECT DATETIME as "시간"
FROM ANIMAL_INS
ORDER by DATETIME
LIMIT 1

-------------

WITH RECURSIVE COUNTER(HOUR) AS (
    SELECT 0 #비반복문
    UNION ALL #UNION 구문
    SELECT HOUR + 1 FROM COUNTER WHERE HOUR < 23 #recursive 구문
)


SELECT HOUR, COUNT(A.ANIMAL_ID) AS COUNT
FROM COUNTER as C LEFT JOIN
        ANIMAL_OUTS A ON C.HOUR = HOUR(A.DATETIME)
GROUP BY HOUR
ORDER BY HOUR

--------
SELECT HOUR(DATETIME), count(*)
FROM ANIMAL_OUTS
WHERE HOUR(DATETIME) BETWEEN 9 and 19
GROUP BY HOUR(DATETIME)
ORDER BY HOUR(DATETIME)



------
SELECT NAME, count(NAME)
FROM ANIMAL_INS
GROUP BY NAME
HAVING count(NAME)> 1
ORDER BY NAME


-----
SELECT ANIMAL_TYPE , count(*) as "count"
FROM ANIMAL_INS
order by ANIMAL_TYPE
GROUP by ANIMAL_TYPE

-----
SELECT ANIMAL_TYPE,(CASE WHEN NAME is null then "No name" else NAME END) as NAME, SEX_UPON_INTAKE
FROM ANIMAL_INS
ORDER BY ANIMAL_ID

----
SELECT ANIMAL_ID
FROM ANIMAL_INS
WHERE NAME is not null

----
SELECT ANIMAL_ID
FROM ANIMAL_INS
WHERE name = null

---
SELECT B.ANIMAL_ID, B.NAME
FROM  ANIMAL_INS A Right JOIN ANIMAL_OUTS B ON A.ANIMAL_ID = B.ANIMAL_ID
WHERE A.ANIMAL_ID is null
ORDER BY ANIMAL_ID

---
SELECT A.NAME, A.DATETIME
FROM ANIMAL_INS A left Join ANIMAL_OUTS B on A.ANIMAL_ID = B.ANIMAL_ID
WHERE B.ANIMAL_ID is null -- 입양이 못가야 하니깐 테이블에서 비워져야 한다.
ORDER BY A.DATETIME
limit 3

----
SELECT B.ANIMAL_ID, B.ANIMAL_TYPE,B.NAME
FROM ANIMAL_INS A inner JOIN ANIMAL_OUTS B on A.ANIMAL_ID = B.ANIMAL_ID
WHERE (A.SEX_UPON_INTAKE like "Intact%")
and ((B.SEX_UPON_OUTCOME like "Neutered%") or ( B.SEX_UPON_OUTCOME like "Spayed%"))

----
SELECT ANIMAL_ID, NAME, date_format(DATETIME, '%Y-%m-%d') as "날짜"
FROM ANIMAL_INS

----
SELECT B.ANIMAL_ID, B.NAME
FROM ANIMAL_INS A RIGHT JOIN ANIMAL_OUTS B on A.ANIMAL_ID = B.ANIMAL_ID
ORDER BY B.DATETIME - A.DATETIME DESC
LIMIT 2


----
SELECT ANIMAL_ID, NAME, (case when SEX_UPON_INTAKE like "Intact%" then
                     'X' else 'O' end) as "중성화"
FROM ANIMAL_INS
ORDER BY ANIMAL_ID




------
SELECT ANIMAL_ID, NAME, SEX_UPON_INTAKE
FROM ANIMAL_INS
WHERE NAME in ("Lucy","Ella", 'Pickle', 'Rogan','Sabrina', 'Mitty')